@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":HrManagerParser" as HrManagerParser LOGIC_COLOR
participant ":DeleteCandidateCommandParser" as DeleteCandidateCommandParser LOGIC_COLOR
participant "d:DeleteCandidateCommand" as DeleteCandidateCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delete_c 1")
activate LogicManager

LogicManager -> HrManagerParser : parseCommand("delete_c 1")
activate HrManagerParser

create DeleteCandidateCommandParser
HrManagerParser -> DeleteCandidateCommandParser
activate DeleteCandidateCommandParser

DeleteCandidateCommandParser --> HrManagerParser
deactivate DeleteCandidateCommandParser

HrManagerParser -> DeleteCandidateCommandParser : parse("1")
activate DeleteCandidateCommandParser

create DeleteCandidateCommand
DeleteCandidateCommandParser -> DeleteCandidateCommand
activate DeleteCandidateCommand

DeleteCandidateCommand --> DeleteCandidateCommandParser : d
deactivate DeleteCandidateCommand

DeleteCandidateCommandParser --> HrManagerParser : d
deactivate DeleteCandidateCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteCandidateCommandParser -[hidden]-> HrManagerParser
destroy DeleteCandidateCommandParser

HrManagerParser --> LogicManager : d
deactivate HrManagerParser

LogicManager -> DeleteCandidateCommand : execute()
activate DeleteCandidateCommand

DeleteCandidateCommand -> Model : deletePerson(p)
activate Model

Model --> DeleteCandidateCommand
deactivate Model

DeleteCandidateCommand -> Model : deletePersonFromInterview(p)
activate Model

Model --> DeleteCandidateCommand
deactivate Model

create CommandResult
DeleteCandidateCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteCandidateCommand
deactivate CommandResult

DeleteCandidateCommand --> LogicManager : result
deactivate DeleteCandidateCommand

[<--LogicManager
deactivate LogicManager
@enduml
