@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyHrManager <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface Model <<Interface>>
Class HrManager
Class ReadOnlyHrManager
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs


Class UniquePersonList
Class UniquePositionList
Class UniqueInterviewList
Class Person
Class Position
Class Interview

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

HrManager .up.|> ReadOnlyHrManager

ModelManager .up.|> Model
Model .left.> ReadOnlyUserPrefs
Model .right.> ReadOnlyHrManager
ModelManager -left-> "1" HrManager
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

HrManager *--> "1" UniquePositionList
HrManager *--> "1" UniqueInterviewList
HrManager *--> "1" UniquePersonList
UniquePersonList --> "~* all" Person
UniquePositionList --> "~* all" Position
UniqueInterviewList --> "~* all" Interview

ModelManager -->"~* filtered" Position
ModelManager -->"~* filtered" Person
ModelManager -->"~* filtered" Interview
@enduml
